
[build]
target = "x86_64-blog_os.json"

[target.i686-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "linker=rust-lld",
    "-C", "relocation-model=static",
]

# (MIGHT) not work, use "-Zbuild-std=core,compiler_builtins" instead
[unstable]
build-std = ["core", "compiler_builtins"]